version: '3.1'

# Describes the dependencies needed for the service to function
services:
  cassandra:
    image: cassandra:3.11.1
    ports:
      - "9042:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients

# docker exec -it <container_id> cqlsh